---
- name: Register client to Landscape server
  hosts:  "{{ hostname }}"
  become: yes
  become_method: sudo
   vars:
    landscape_account_name: standalone
    landscape_url: https://10.0.16.90/message-system
    landscape_ping_url: http://10.0.16.90/ping

  tasks:
    - name: Skip non-Ubuntu systems (info only)
      debug:
        msg: "Skipping {{ inventory_hostname }} ({{ ansible_distribution }}) — not Ubuntu."
      when: ansible_distribution != "Ubuntu"

    - name: Enable 'universe' repo (Ubuntu only)
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
        state: present
        filename: universe
      when: ansible_distribution == "Ubuntu"

    - name: Update apt cache (Ubuntu only)
      apt:
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install landscape-client (Ubuntu only)
      apt:
        name: landscape-client
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Get hostname (Ubuntu only)
      command: hostname
      register: hostname_result
      when: ansible_distribution == "Ubuntu"

    - name: Register machine with Landscape (Ubuntu only)
      command: >
        landscape-config
        --computer-title "{{ hostname_result.stdout }}"
        --account-name {{ landscape_account_name }}
        --url {{ landscape_url }}
        --ping-url {{ landscape_ping_url }}
      args:
        creates: /etc/landscape/client.conf
      when: ansible_distribution == "Ubuntu"

    - name: Start and enable landscape-client service (Ubuntu only)
      service:
        name: landscape-client
        state: started
        enabled: true
      when: ansible_distribution == "Ubuntu"