---
- name: Register Ubuntu clients to Landscape server
  hosts: "{{ hostname }}"  # Replace with your host or group name
  become: yes
  become_method: sudo
  vars:
    landscape_account_name: standalone
    landscape_url: https://10.0.16.90/message-system
    landscape_ping_url: http://10.0.16.90/ping
    registration_key: C12eq3PMGTYxCWLZd1bEVXzX64GfSt
    script_users: pablo
    access_group: pablo
    min_required_space_mb: 200  # Minimum disk space required (in MB)

  tasks:
    - name: Check available disk space on /
      shell: df --output=avail -m / | tail -1
      register: disk_free
      changed_when: false

    - name: Fail if available disk space is below threshold
      fail:
        msg: "Not enough disk space available ({{ disk_free.stdout }}MB). Minimum required: {{ min_required_space_mb }}MB."
      when: disk_free.stdout | int < min_required_space_mb

    - name: Free up space - clean apt cache
      apt:
        autoclean: yes
        autoremove: yes
      when: ansible_distribution == "Ubuntu"

    - name: Enable 'universe' repo (Ubuntu only)
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
        state: present
        filename: universe
      when: ansible_distribution == "Ubuntu"

    - name: Update apt cache (Ubuntu only)
      apt:
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install landscape-client (Ubuntu only)
      apt:
        name: landscape-client
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Copy landscape server certificates to /etc/ssl/certs (Ubuntu only)
      copy:
        src: "{{ item }}"
        dest: "/etc/ssl/certs/{{ item }}"
        mode: '0644'
      with_items:
        - landscape_server.pem
        - landscape_server_ca.crt
        - ca-certificates.crt
      when: ansible_distribution == "Ubuntu"

    - name: Update CA certificates (Ubuntu only)
      command: update-ca-certificates
      when: ansible_distribution == "Ubuntu"

    - name: Get hostname (Ubuntu only)
      command: hostname
      register: hostname_result
      when: ansible_distribution == "Ubuntu"

    - name: Register machine with Landscape (Ubuntu only)
      command: >
        landscape-config
        --computer-title "{{ hostname_result.stdout }}"
        --account-name "{{ landscape_account_name }}"
        --url "{{ landscape_url }}"
        --ping-url "{{ landscape_ping_url }}"
        --registration-key "{{ registration_key }}"
        --script-users "{{ script_users }}"
        --access-group "{{ access_group }}"
      args:
        creates: /etc/landscape/client.conf
      when: ansible_distribution == "Ubuntu"

    - name: Start and enable landscape-client service (Ubuntu only)
      service:
        name: landscape-client
        state: started
        enabled: true
      when: ansible_distribution == "Ubuntu"
