---
- name: Register client to Landscape server
  hosts:  "{{ hostname }}"
  become: yes
  become_method: sudo
  vars:
    landscape_account_name: standalone
    landscape_url: https://10.0.16.90/message-system
    landscape_ping_url: http://10.0.16.90/ping

  tasks:
    - name: Enable 'universe' repo on Ubuntu only
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
        state: present
        filename: universe
      when: ansible_distribution == "Ubuntu"

    - name: Update apt cache
      apt:
        update_cache: true

    - name: Ensure landscape-client is installed
      apt:
        name: landscape-client
        state: present

    - name: Get the hostname
      command: hostname
      register: hostname_result

    - name: Register the machine with Landscape
      command: >
        landscape-config
        --computer-title "{{ hostname_result.stdout }}"
        --account-name {{ landscape_account_name }}
        --url {{ landscape_url }}
        --ping-url {{ landscape_ping_url }}
      args:
        creates: /etc/landscape/client.conf

    - name: Start landscape-client service
      service:
        name: landscape-client
        state: started
        enabled: true