# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: Ubuntuclients
  become: true

  tasks:

- name: Call Roles
  hosts: buntuclients
  become: ture
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
