# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 10.0.90.101
  become: true

  tasks:

- name: Call Roles
  hosts: 10.0.90.101
  #become: true
  ansible_become: yes 
  ansible_become_method: sudo
  ansible_become_pass: "12345678"
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
