---
- name: Set system time and timezone to Canada/Montreal
  hosts: "{{ hostname }}"  # Replace with your hostname or inventory group name
  become: yes
  become_method: sudo
  tasks:

    - name: Gather facts
      ansible.builtin.setup:

    - name: Set the timezone to Canada/Montreal using timedatectl
      command: timedatectl set-timezone America/Montreal

    - name: Ensure ntp is installed and started (for time synchronization)
      apt:
        name: ntp
        state: present
        update_cache: yes

    - name: Ensure NTP service is enabled and started
      service:
        name: ntp
        state: started
        enabled: yes

    - name: Check if ansible_date_time fact is available
      debug:
        msg: "ansible_date_time fact is available"
      when: ansible_facts.get('ansible_date_time') is not none

    - name: Set a variable for the current timezone
      set_fact:
        current_timezone: "{{ ansible_facts['ansible_date_time']['tz'] }}"
      when: ansible_facts.get('ansible_date_time') is not none

    - name: Synchronize the system time using NTP
      command: ntpdate pool.ntp.org
      when: ansible_facts.get('ansible_date_time') is not none and ansible_facts['ansible_date_time']['tz'] != 'America/Montreal'

    - name: Verify the time
      command: date
      register: system_time

    - name: Print the system time to verify
      debug:
        var: system_time.stdout
