---
- name: Apply security updates on Ubuntu 24.04 and log system info
  hosts: '{{ hostname }}'
  become: yes
  become_method: sudo
  vars:
    log_file: "/tmp/security_updates_log.json"  # Safer path for AWX environments
    system_ip: "{{ ansible_default_ipv4.address }}"
    ubuntu_version: "{{ ansible_lsb.release }}"
    kernel_version: "{{ ansible_kernel }}"

  tasks:
    - name: Gather full system facts
      ansible.builtin.setup:

    - name: Ensure log file exists
      become: yes
      file:
        path: "{{ log_file }}"
        state: touch
        mode: "0644"
        owner: root
        group: root

    - name: Get logged in users and their IPs
      command: "who"
      register: users_connected
      ignore_errors: yes
      no_log: true

    - name: Parse user connections and log them
      set_fact:
        user_info: |
          {% set users = [] %}
          {% for line in users_connected.stdout_lines %}
            {% set parts = line.split() %}
            {% if parts|length > 3 %}
              {% set user = parts[0] %}
              {% set ip = parts[2] %}
              {% set users = users + [{'user': user, 'ip': ip}] %}
            {% endif %}
          {% endfor %}
          {{ users }}
      when: users_connected.stdout_lines is defined

    - name: Log user connections in JSON format
      become: yes
      copy:
        content: |
          {
            "date": "{{ ansible_date_time.iso8601 }}",
            "hostname": "{{ inventory_hostname }}",
            "ip_address": "{{ system_ip }}",
            "ubuntu_version": "{{ ubuntu_version }}",
            "kernel_version": "{{ kernel_version }}",
            "uptime": "{{ ansible_uptime_seconds | int // 86400 }} days",
            "task": "Log user connections",
            "user_connections": {{ user_info | to_json }}
          }
        dest: "{{ log_file }}"
        mode: "0644"
        owner: root
        group: root
        append: yes

    - name: Update package cache
      apt:
        update_cache: yes
      register: apt_cache_update
      ignore_errors: yes
      no_log: true

    - name: Log the update cache result
      become: yes
      copy:
        content: |
          {
            "date": "{{ ansible_date_time.iso8601 }}",
            "hostname": "{{ inventory_hostname }}",
            "ip_address": "{{ system_ip }}",
            "ubuntu_version": "{{ ubuntu_version }}",
            "kernel_version": "{{ kernel_version }}",
            "uptime": "{{ ansible_uptime_seconds | int // 86400 }} days",
            "task": "Update package cache",
            "status": "{{ 'success' if apt_cache_update.rc == 0 else 'failure' }}",
            "stdout": {{ apt_cache_update.stdout | default('"No output"') | to_json }},
            "stderr": {{ apt_cache_update.stderr | default('"No error"') | to_json }},
            "return_code": {{ apt_cache_update.rc }}
          }
        dest: "{{ log_file }}"
        mode: "0644"
        owner: root
        group: root
        append: yes

    - name: Install security updates
      command: "apt-get upgrade -y --only-upgrade"
      register: update_result
      ignore_errors: yes
      no_log: true

    - name: Log the update result
      become: yes
      copy:
        content: |
          {
            "date": "{{ ansible_date_time.iso8601 }}",
            "hostname": "{{ inventory_hostname }}",
            "ip_address": "{{ system_ip }}",
            "ubuntu_version": "{{ ubuntu_version }}",
            "kernel_version": "{{ kernel_version }}",
            "uptime": "{{ ansible_uptime_seconds | int // 86400 }} days",
            "task": "Install security updates",
            "status": "{{ 'success' if update_result.rc == 0 else 'failure' }}",
            "stdout": {{ update_result.stdout | default('"No output"') | to_json }},
            "stderr": {{ update_result.stderr | default('"No error"') | to_json }},
            "return_code": {{ update_result.rc }}
          }
        dest: "{{ log_file }}"
        mode: "0644"
        owner: root
        group: root
        append: yes

    - name: Check for upgradable packages
      command: "apt list --upgradable"
      register: upgradable_result
      ignore_errors: yes
      no_log: true

    - name: Log upgradable packages check result
      become: yes
      copy:
        content: |
          {
            "date": "{{ ansible_date_time.iso8601 }}",
            "hostname": "{{ inventory_hostname }}",
            "ip_address": "{{ system_ip }}",
            "ubuntu_version": "{{ ubuntu_version }}",
            "kernel_version": "{{ kernel_version }}",
            "uptime": "{{ ansible_uptime_seconds | int // 86400 }} days",
            "task": "Check for upgradable packages",
            "status": "{{ 'success' if upgradable_result.rc == 0 else 'failure' }}",
            "stdout": {{ upgradable_result.stdout | default('"No upgradable packages"') | to_json }},
            "stderr": {{ upgradable_result.stderr | default('"No error"') | to_json }},
            "return_code": {{ upgradable_result.rc }}
          }
        dest: "{{ log_file }}"
        mode: "0644"
        owner: root
        group: root
        append: yes

    - name: Output final upgrade status
      debug:
        msg: "Upgrade completed with status {{ update_result.rc }}"
