---    
- hosts: '{{ hostname }}'
  become: yes
  become_method: sudo
  tasks:
      - name: Update all packages on a Debian/Ubuntu
        apt:
            update_cache: yes
            upgrade: dist