---
- name: Apply security updates on Ubuntu 24.04
  hosts: '{{ hostname }}'
  become: yes
  become_method: sudo
  vars:
    log_file: "/var/log/ansible/security_updates_log.json"  # Define the log file location
    system_ip: "{{ ansible_default_ipv4.address }}"  # Capture the system's IP address
  tasks:

    # Ensure the /var/log/ansible directory exists
    - name: Ensure the /var/log/ansible directory exists
      file:
        path: "/var/log/ansible"
        state: directory
        mode: "0755"

    # Ensure log file exists or create it
    - name: Ensure log file exists
      file:
        path: "{{ log_file }}"
        state: touch
        mode: "0644"

    # Update package cache
    - name: Update package cache
      apt:
        update_cache: yes
      register: apt_cache_update
      ignore_errors: yes
      no_log: true

    # Log the update cache result in JSON format
    - name: Log the update cache result
      copy:
        content: |
          {
            "date": "{{ ansible_date_time.iso8601 }}",
            "hostname": "{{ inventory_hostname }}",
            "ip_address": "{{ system_ip }}",
            "task": "Update package cache",
            "status": "{{ 'success' if apt_cache_update.rc == 0 else 'failure' }}",
            "stdout": "{{ apt_cache_update.stdout | default('No output') }}",
            "stderr": "{{ apt_cache_update.stderr | default('No error') }}",
            "return_code": "{{ apt_cache_update.rc }}"
          }
        dest: "{{ log_file }}"
        mode: "0644"
        append: yes  # Append the result to the log file

    # Install security updates
    - name: Install security updates
      command: "apt-get upgrade -y --only-upgrade"
      register: update_result
      ignore_errors: yes
      no_log: true

    # Log the update result in JSON format
    - name: Log the update result
      copy:
        content: |
          {
            "date": "{{ ansible_date_time.iso8601 }}",
            "hostname": "{{ inventory_hostname }}",
            "ip_address": "{{ system_ip }}",
            "task": "Install security updates",
            "status": "{{ 'success' if update_result.rc == 0 else 'failure' }}",
            "stdout": "{{ update_result.stdout | default('No output') }}",
            "stderr": "{{ update_result.stderr | default('No error') }}",
            "return_code": "{{ update_result.rc }}"
          }
        dest: "{{ log_file }}"
        mode: "0644"
        append: yes  # Append the result to the log file

    # Check for upgradable packages (optional, for logging purposes)
    - name: Check for upgradable packages
      command: "apt list --upgradable"
      register: upgradable_result
      ignore_errors: yes
      no_log: true

    # Log the upgradable packages check result in JSON format
    - name: Log upgradable packages check result
      copy:
        content: |
          {
            "date": "{{ ansible_date_time.iso8601 }}",
            "hostname": "{{ inventory_hostname }}",
            "ip_address": "{{ system_ip }}",
            "task": "Check for upgradable packages",
            "status": "{{ 'success' if upgradable_result.rc == 0 else 'failure' }}",
            "stdout": "{{ upgradable_result.stdout | default('No upgradable packages') }}",
            "stderr": "{{ upgradable_result.stderr | default('No error') }}",
            "return_code": "{{ upgradable_result.rc }}"
          }
        dest: "{{ log_file }}"
        mode: "0644"
        append: yes  # Append the result to the log file

    # Output the final status of the upgrade process
    - name: Output final upgrade status
      debug:
        msg: "Upgrade completed with status {{ update_result.rc }}"
