---
- name: Install and configure Promtail to send logs to Loki
  hosts: "{{ hostname }}"
  become: yes
  become_method: sudo
  vars:
    promtail_version: "2.7.1"
    promtail_bin: "/usr/local/bin/promtail"
    promtail_config_file: "/etc/promtail/config.yml"
    loki_url: "http://10.0.16.252:3100/loki/api/v1/push"

  tasks:
    - name: Ensure required packages are installed (unzip, curl)
      apt:
        name:
          - unzip
          - curl
        state: present
        update_cache: yes

    - name: Download Promtail binary
      get_url:
        url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-amd64.zip"
        dest: "/tmp/promtail-linux-amd64.zip"

    - name: Unzip Promtail binary
      unarchive:
        src: "/tmp/promtail-linux-amd64.zip"
        dest: "/tmp"
        remote_src: yes

    - name: Move Promtail binary to /usr/local/bin
      command:
        cmd: mv /tmp/promtail-linux-amd64 /usr/local/bin/promtail
        creates: "{{ promtail_bin }}"

    - name: Make Promtail executable
      file:
        path: "{{ promtail_bin }}"
        mode: '0755'

    - name: Create Promtail configuration directory
      file:
        path: "/etc/promtail"
        state: directory
        mode: '0755'

    - name: Create Promtail configuration file
      copy:
        dest: "{{ promtail_config_file }}"
        content: |
          server:
            http_listen_port: 9080
            grpc_listen_port: 9095

          positions:
            filename: /tmp/positions.yaml

          clients:
            - url: "{{ loki_url }}"

          scrape_configs:
            - job_name: system_logs
              static_configs:
                - targets:
                    - localhost
                  labels:
                    job: varlogs
                    __path__: |
                      /var/log/*.log
                      /var/log/syslog
                      /tmp/security_updates_log.json
        mode: '0644'

    - name: Create Promtail systemd service file
      copy:
        dest: "/etc/systemd/system/promtail.service"
        content: |
          [Unit]
          Description=Promtail - Log shipping agent for Loki
          After=network.target

          [Service]
          ExecStart={{ promtail_bin }} -config.file={{ promtail_config_file }}
          Restart=on-failure
          User=root

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd to pick up the Promtail service
      systemd:
        daemon_reload: yes

    - name: Validate Promtail config before starting
      command: "{{ promtail_bin }} -config.file={{ promtail_config_file }} -log.level=debug -dry-run"
      register: promtail_config_test
      failed_when: "'error' in promtail_config_test.stderr.lower()"
      ignore_errors: false

    - name: Enable and start Promtail service
      systemd:
        name: promtail
        enabled: yes
        state: started
