---
- name: Reboot Ubuntu Servers
  hosts: "{{ hostname | default('all') }}"
  become: yes
  become_method: sudo
  tasks:
    - name: Create bash script to reboot the server
      copy:
        content: |
          #!/bin/bash
          sudo /sbin/shutdown -r now
        dest: /tmp/reboot_server.sh
        mode: '0755'

    - name: Execute the bash script with sudo
      command: sudo /tmp/reboot_server.sh
      register: reboot_status
      ignore_errors: yes

    - name: Clean up the bash script after execution
      file:
        path: /tmp/reboot_server.sh
        state: absent

    - name: Verify server is back online (ping test)
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        timeout: 600
      delegate_to: localhost

    - name: Confirm reboot was successful
      debug:
        msg: "Reboot initiated and the server is back online."
      when: reboot_status.rc == 0
