---
- name: Reboot Ubuntu Servers
  hosts: "{{ hostname | default('all') }}"
  become: yes
  become_method: sudo
  become_flags: '-S'  # Ensures sudo does not prompt for a password

  tasks:
    - name: Reboot the server
      command: /sbin/shutdown -r now
      register: reboot_status
      ignore_errors: yes  # Allow to continue even if reboot fails

    - name: Wait for server to come back online
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22  # SSH port to check if the server is back online
        state: started
        delay: 10  # Wait 10 seconds before checking again
        timeout: 300  # Maximum 5 minutes to wait for the server to be back online

    - name: Confirm reboot was successful
      debug:
        msg: "Server {{ inventory_hostname }} has been successfully rebooted."
      when: reboot_status.rc == 0  # Only run this task if the reboot succeeded
