---
- name: Verify high-priority vulnerable packages and update
  hosts: '{{ hostname }}'
  become: yes
  become_method: sudo
  vars:
    log_file: "/var/log/ansible/security_update_log.txt"
    high_priority_cves:
      - package: "openssl"
        cve: "CVE-2021-3450"
        version: "1.1.1k-1ubuntu3.1"
      - package: "libcurl3"
        cve: "CVE-2020-8231"
        version: "7.68.0-1ubuntu2.6"
      # Add more CVEs as needed

  tasks:
    - name: Ensure log file exists
      file:
        path: "{{ log_file }}"
        state: touch
        mode: "0644"

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Check installed packages
      command: "dpkg-query -W -f='${Package} ${Version}\n'"
      register: installed_packages

    - name: Log installed packages
      blockinfile:
        path: "{{ log_file }}"
        create: yes
        block: |
          === Installed Packages ({{ ansible_date_time.iso8601 }}) ===
          {{ installed_packages.stdout }}

    - name: Compare installed packages with known vulnerable packages
      set_fact:
        vulnerable_packages: >-
          {{
            high_priority_cves
            | selectattr('package', 'in', installed_packages.stdout_lines | map('split', ' ') | map('first') | list)
            | list
          }}

    - name: Install updates for vulnerable packages
      apt:
        name: "{{ item.package }}"
        state: latest
      loop: "{{ vulnerable_packages }}"
      register: update_result
      when: vulnerable_packages | length > 0

    # - name: Log the updates applied
    #   blockinfile:
    #     path: "{{ log_file }}"
    #     create: yes
    #     block: |
    #       === Applied Updates ({{ ansible_date_time.iso8601 }}) ===
    #       {{ update_result.results | map(attribute='stdout') | join('\n') }}
    #   when: update_result is defined

    - name: Ensure the system is fully updated if no CVE matches
      apt:
        upgrade: dist
        update_cache: yes
      register: full_upgrade_result
      when: vulnerable_packages | length == 0

    - name: Log the full upgrade result
      blockinfile:
        path: "{{ log_file }}"
        create: yes
        block: |
          === Full Upgrade Output ({{ ansible_date_time.iso8601 }}) ===
          {{ full_upgrade_result.stdout }}
      when: full_upgrade_result is defined

    - name: Output completion message
      debug:
        msg: "Vulnerable packages have been checked and updated. Log is available at {{ log_file }}"
