---
- name: Apply security updates on Ubuntu 24.04
  hosts: '{{ hostname }}
  become: yes
  become_user: root
  vars:
    log_file: "/var/log/ansible/security_updates.log"  # Define the log file location

  tasks:
    - name: Ensure the /var/log/ansible directory exists
      file:
        path: "/var/log/ansible"
        state: directory
        mode: "0755"

    - name: Ensure log file exists
      file:
        path: "{{ log_file }}"
        state: touch
        mode: "0644"

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install security updates
      apt:
        upgrade: security
      register: update_result

    - name: Log update results
      copy:
        content: "{{ update_result.stdout }}"
        dest: "{{ log_file }}"
      when: update_result.stdout is defined
