---
- name: Apply security updates on Ubuntu 24.04
  hosts: "{{ hostname | default('all') }}"
  become: yes
  become_method: sudo
  vars:
    log_dir: "/var/tmp/ansible_logs"
    log_file: "{{ log_dir }}/security_updates.log"

  tasks:
    - name: Ensure the log directory exists
      become: yes
      file:
        path: "{{ log_dir }}"
        state: directory
        mode: "0755"

    - name: Ensure the log file exists
      become: yes
      file:
        path: "{{ log_file }}"
        state: touch
        mode: "0644"

    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Perform security upgrade
      become: yes
      shell: |
        apt list --upgradable
        apt-get -s upgrade | grep -i security || echo "No security updates available"
        apt-get upgrade -y --only-upgrade
      register: upgrade_output
      changed_when: "'upgraded' in upgrade_output.stdout or 'upgraded' in upgrade_output.stderr"
      ignore_errors: yes

    - name: Log the update results
      become: yes
      copy:
        content: |
          ===== Security Update Log =====
          Date: {{ ansible_date_time.iso8601 }}
          Host: {{ inventory_hostname }}
          --------------------------------
          {{ upgrade_output.stdout | default('No output captured') }}
        dest: "{{ log_file }}"


    # - name: Send log via email
    #   mail:
    #     host: "smtp.mailjet.com"
    #     port: 587
    #     username: "{{ mailjet_api_key }}"
    #     password: "{{ mailjet_secret_key }}"
    #     to: "recipient@example.com"
    #     subject: "Security Updates Applied"
    #     body: "{{ update_result.stdout }}"
    #     from: "your_email@example.com"
    #     smtp_tls: yes
    #   when: update_result.stdout is defined
